### ISSUE TITLE
Upload the first assigment (Assignment 1) 

### ISSUE THREAD

**Issue by Ramseyxlil** [Ramseyxlil/SCA-TechnicalWriting#2]
Upload the first assigment (Assignment 1) to the branch you will create check the assignment doc or readme on how to do that

**Comment by Ngoabby** [comment]
[Iron User Manua-WPS Office.docx](https://github.com/user-attachments/files/15858082/Iron.User.Manua-WPS.Office.docx)
I'm I'm working on the first assignment.

**Comment by Ngoabby** [comment]
Please sir, I can't carry out number 3 instruction. I can't type. It's showing share, copy..... What should I do?

**Comment by Ramseyxlil** [comment]
> Please sir, I can't carry out number 3 instruction. I can't type. It's showing share, copy..... What should I do?

You are meant to type it on Microsoft word or any editor then upload to GitHub

**Comment by Am2favoured** [comment]
I'm working on uploading my first assignment

**Comment by Am2favoured** [comment]
Fixed by Favour #<03902d7>
