### ISSUE TITLE
Upload the first assigment (Assignment 2)

### ISSUE THREAD

**Issue by Ramseyxlil** [Ramseyxlil/SCA-TechnicalWriting#3]
Upload the first assigment (Assignment 2) to the branch you will create check the assignment doc or readme on how to do that

**Comment by Enuma75G** [comment]
[TECHNICAL WRITING [ASS 2].pdf](https://github.com/user-attachments/files/15892111/TECHNICAL.WRITING.ASS.2.pdf)

I already submitted the first Assignment (Assignment 2)
